name: CI
on: [push, pull_request]

jobs:
  build:

    runs-on: macOS-14

    steps:
    - uses: actions/checkout@v5

    - uses: maxim-lobanov/setup-xcode@v1.6.0
      with:
        xcode-version: 15.4

    - name: Build
      run: swift run SwiftFileTools
